org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

org.gradle.configuration-cache=false

minecraft_version=26.3
loader_version=0.19.5
loom_version=1.17-SNAPSHOT

version=1.4.12
group=com.vnap

fabric_api_version=0.160.7+26.3
emf_version=p8M0c1vN
etf_version=5wNzCsUb
modmenu_version=20.0.2

dialogue_test_command=false
