textures.1=1
name.1=jeb_

textures.2=1
colors.2=white

textures.3=2
colors.3=light_gray

textures.4=3
colors.4=gray

textures.5=4
colors.5=black

textures.6=5
colors.6=brown

textures.7=6
colors.7=red

textures.8=7
colors.8=orange

textures.9=8
colors.9=yellow

textures.10=9
colors.10=lime

textures.11=10
colors.11=green

textures.12=11
colors.12=cyan

textures.13=12
colors.13=light_blue

textures.14=13
colors.14=blue

textures.15=14
colors.15=purple

textures.16=15
colors.16=magenta

textures.17=16
colors.17=pink